version: '3.7'

services:
  redis:
    image: redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass $${REDIS_PASSWORD:?REDIS_PASSWORD is not configured on the .env file}
    ports:
      - "6379:6379"
    env_file:
      - redis.env